# Generated by Django 3.1.4 on 2020-12-22 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9950)])),
            ],
        ),
        migrations.CreateModel(
            name='New_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('infected', models.BooleanField(default=False)),
                ('exposed', models.BooleanField(default=False)),
                ('healthy', models.BooleanField(default=False)),
            ],
        ),
    ]
