# Generated by Django 3.1.4 on 2020-12-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_cities_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_post',
            name='exposed',
        ),
        migrations.RemoveField(
            model_name='new_post',
            name='healthy',
        ),
        migrations.RemoveField(
            model_name='new_post',
            name='infected',
        ),
        migrations.AddField(
            model_name='new_post',
            name='diagnosis',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
