# Generated by Django 3.1.4 on 2020-12-22 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0003_auto_20201222_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_post',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='new_post',
            name='state',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='new_post',
            name='zip',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(9950)]),
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
