# Generated by Django 3.1.4 on 2020-12-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0004_auto_20201222_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_post',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
