# Generated by Django 3.1.4 on 2020-12-30 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0005_new_post_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_post',
            name='zip',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(99950)]),
        ),
    ]
